[package]
name = "hermes"
version = "1.0.0"
authors = []

[addresses]
hermes="0x16f82cf127ba58ade1c2b6bb19adfdde96054aae1febf0ce1b6e805b98d5a451"
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
