[package]
name = "hermes"
version = "1.0.0"
authors = []

[addresses]
hermes="0xaf58b8a7f94ecf3666c008312c14bd04bb1cde3ea8f182bb9706be47f598f3b5"
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
